api_login_check:
    path: /api/login_check

user_controllers:
    resource: ../src/User/Adapter/Framework/Http/Controller/
    type: annotation
    prefix: /api/user
    trailing_slash_on_root: false